@@include('vendor/smoothScroll.js', {})
@@include('vendor/inputmask.min.js', {})
@@include('vendor/swiper.min.js', {})
@@include('vendor/nouislider.js', {})
@@include('vendor/wNumb.min.js', {})
@@include('vendor/lightgallery.min.js', {})
@@include('vendor/tippy.js', {})
@@include('vendor/datepicker-full.min.js', {})